#!/usr/bin/env bash
# Theme switcher script for Reanimation Terminal

set -e

# Available themes
THEMES=("dracula" "nord" "solarized-dark")

# Kitty config path
KITTY_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/kitty/kitty.conf"

# Function to switch theme
switch_theme() {
  local theme="$1"
  if [[ ! " ${THEMES[@]} " =~ " ${theme} " ]]; then
    echo "Error: Theme '$theme' not found. Available themes: ${THEMES[*]}"
    exit 1
  fi

  # Update the theme in the config (this assumes the config is generated by Nix)
  # In practice, you'd need to regenerate the Nix config or use kitty's dynamic config
  echo "Switching to theme: $theme"
  kitty @ set-colors --all "$KITTY_CONFIG" # This is a placeholder; actual switching would require kitty's API

  # For dynamic switching, you could use kitty's remote control
  # kitty @ set-colors --all /path/to/theme.conf

  echo "Theme switched to $theme. Restart Kitty or reload config to apply."
}

# Main script
if [[ $# -eq 0 ]]; then
  echo "Usage: $0 <theme>"
  echo "Available themes: ${THEMES[*]}"
  exit 1
fi

switch_theme "$1"
